"""
schemas.py
Pydantic models defining the contract between perception module and backend.

IncidentIn: EXACTLY what perception/incident_sender.py sends
IncidentOut: what backend returns (adds agent reasoning + status)
ZoneOccupancy: live occupancy data from perception module
"""



from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime


# ============================================================================
# INCIDENT SCHEMAS
# ============================================================================

class IncidentIn(BaseModel):
    #incident from perception module
    incident_id: str = Field(..., description="Unique ID generated by perception module")
    type: str = Field(..., description="'overcrowding' | 'unattended_baggage' | 'intrusion' | 'fire'")
    zone: Optional[str] = Field(None, description="Zone name where incident occurred")
    timestamp: str = Field(..., description="ISO 8601 timestamp from perception module")
    tracked_object_id: Optional[int] = Field(None, description="For baggage/intrusion: which tracked object ID")
    dwell_time_seconds: Optional[float] = Field(None, description="For baggage: how long object stationary")
    detection_confidence: Optional[float] = Field(None, description="YOLO confidence (0-1)")
    count: Optional[int] = Field(None, description="For overcrowding: person count in zone")

    class Config:
        json_schema_extra = {
            "example": {
                "incident_id": "inc_a1b2c3d4",
                "type": "unattended_baggage",
                "zone": "Gate_3",
                "timestamp": "2026-08-19T14:32:10Z",
                "tracked_object_id": 47,
                "dwell_time_seconds": 32.5,
                "detection_confidence": 0.89
            }
        }


class AgentOutput(BaseModel):

    #What the LLM agent produces after analyzing an incident.

    severity: str = Field(..., description="'critical' | 'high' | 'medium' | 'low'")
    reasoning_summary: str = Field(..., description="Short explanation of severity assignment")
    correlated_incident_ids: List[str] = Field(
        default_factory=list,
        description="IDs of related recent incidents"
    )
    recommended_action: str = Field(
        ...,
        description="'dispatch_security' | 'verify' | 'monitor' | 'none'"
    )
    notification_draft: str = Field(..., description="Alert message to send to control room")

    class Config:
        json_schema_extra = {
            "example": {
                "severity": "high",
                "reasoning_summary": "Unattended bag at Gate 3 for 32s, owner seen leaving rapidly",
                "correlated_incident_ids": ["inc_a1b2c2d0"],
                "recommended_action": "dispatch_security",
                "notification_draft": "Unattended bag flagged at Gate 3 — possible abandonment"
            }
        }


class IncidentOut(BaseModel):
    """Full incident as returned to dashboard (combines input + agent output + status)."""
    # Original fields from perception (immutable)
    incident_id: str
    type: str
    zone: Optional[str]
    timestamp: str
    tracked_object_id: Optional[int]
    dwell_time_seconds: Optional[float]
    detection_confidence: Optional[float]
    count: Optional[int]

    # Agent analysis (added by backend, can be overridden)
    severity: Optional[str] = None
    reasoning_summary: Optional[str] = None
    correlated_incident_ids: List[str] = Field(default_factory=list)
    recommended_action: Optional[str] = None
    notification_draft: Optional[str] = None

    # Operational status (updated by operators)
    status: str = Field(default="new", description="'new' | 'acknowledged' | 'resolved' | 'false_positive'")
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None

    # Metadata (set by backend)
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True  # allow loading from SQLAlchemy ORM objects


# ============================================================================
# OPERATOR ACTION SCHEMAS
# ============================================================================

class AckRequest(BaseModel):
    """Operator acknowledges an incident."""
    operator_name: str = Field(..., description="Who acknowledged this")


class OverrideRequest(BaseModel):
    """Operator overrides the agent's severity judgment."""
    new_severity: str = Field(..., description="'critical' | 'high' | 'medium' | 'low'")
    reason: str = Field(..., description="Why override (for audit trail)")


class FalsePositiveRequest(BaseModel):
    """Operator marks an incident as a false positive detection."""
    reason: str = Field(..., description="Why this is a false positive")


# ============================================================================
# ZONE OCCUPANCY SCHEMAS
# ============================================================================

class ZoneOccupancy(BaseModel):
    """
    Live occupancy status for a zone - sent regularly by perception module.
    Not an incident, just real-time status information.
    """
    zone: str = Field(..., description="Zone name (Gate_3, Restricted_Lab, etc)")
    current_count: int = Field(..., ge=0, description="People detected right now")
    capacity: int = Field(..., ge=1, description="Max allowed in zone")
    occupancy_percentage: float = Field(..., ge=0, le=200, description="0-100 normal, >100 overcrowded")
    timestamp: str = Field(..., description="ISO 8601 timestamp from perception")
    trend: Optional[str] = Field(None, description="'increasing' | 'stable' | 'decreasing'")

    class Config:
        json_schema_extra = {
            "example": {
                "zone": "Gate_3",
                "current_count": 8,
                "capacity": 10,
                "occupancy_percentage": 80.0,
                "timestamp": "2026-08-19T14:35:22Z",
                "trend": "stable"
            }
        }


class ZoneOccupancyOut(BaseModel):
    """Response from /zones/occupancy endpoints."""
    zone: str
    current_count: int
    capacity: int
    occupancy_percentage: float
    timestamp: str
    trend: Optional[str] = None
    updated_at: datetime

    class Config:
        from_attributes = True