"""
schemas.py
Pydantic V2 models defining the API contract between the perception module, 
backend, and the frontend dashboard.
"""

from datetime import datetime
from typing import List, Literal, Optional
from pydantic import BaseModel, ConfigDict, Field

# ============================================================================
# INCIDENT SCHEMAS (Perception -> Backend -> Frontend)
# ============================================================================

class IncidentIn(BaseModel):
    """
    EXACT payload sent by the perception module when an incident is detected.
    Frontend does NOT send this; it only receives IncidentOut.
    """
    incident_id: str = Field(..., description="Unique ID generated by perception module")
    type: Literal["overcrowding", "unattended_baggage", "intrusion", "fire"]
    zone: Optional[str] = Field(None, description="Zone name where incident occurred")
    timestamp: str = Field(..., description="ISO 8601 timestamp from perception module")
    
    # Perception specific fields
    tracked_object_id: Optional[int] = Field(None, description="For baggage/intrusion: which tracked object ID")
    dwell_time_seconds: Optional[float] = Field(None, description="For baggage: how long object stationary")
    detection_confidence: Optional[float] = Field(None, ge=0, le=1, description="YOLO confidence (0-1)")
    count: Optional[int] = Field(None, ge=0, description="For overcrowding: person count in zone")


class AgentOutput(BaseModel):
    """
    What the LLM agent produces after analyzing an incident. 
    Mapped to DB columns and merged into IncidentOut for the frontend.
    """
    severity: Literal["critical", "high", "medium", "low"]
    reasoning_summary: str
    correlated_incident_ids: List[str] = Field(default_factory=list)
    recommended_action: Literal["dispatch_security", "verify", "monitor", "none"]
    notification_draft: str


class IncidentOut(BaseModel):
    """
    The complete incident object sent to the frontend via REST API and WebSocket.
    Combines raw perception data + LLM agent analysis + operational status.
    """
    # 1. Original perception data
    incident_id: str
    type: str
    zone: Optional[str] = None
    timestamp: str
    tracked_object_id: Optional[int] = None
    dwell_time_seconds: Optional[float] = None
    detection_confidence: Optional[float] = None
    count: Optional[int] = None

    # 2. Agent analysis (added by backend)
    severity: Optional[str] = None
    reasoning_summary: Optional[str] = None
    correlated_incident_ids: List[str] = Field(default_factory=list)
    recommended_action: Optional[str] = None
    notification_draft: Optional[str] = None

    # 3. Operational status (updated by frontend operators)
    status: Literal["new", "acknowledged", "resolved", "false_positive"] = "new"
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None

    # 4. Metadata
    created_at: datetime
    updated_at: datetime

    # Pydantic V2 configuration to allow direct mapping from SQLAlchemy ORM objects
    model_config = ConfigDict(from_attributes=True)


# ============================================================================
# OPERATOR ACTION SCHEMAS (Frontend -> Backend)
# ============================================================================

class AckRequest(BaseModel):
    """Payload sent by the frontend when an operator clicks 'Acknowledge'."""
    operator_name: str = Field(..., description="Who acknowledged this")

class OverrideRequest(BaseModel):
    """Payload sent by the frontend when an operator changes the LLM's severity."""
    new_severity: Literal["critical", "high", "medium", "low"]
    reason: str = Field(..., description="Why override (for audit trail)")

class FalsePositiveRequest(BaseModel):
    """Payload sent by the frontend when an operator dismisses an incident."""
    reason: str = Field(..., description="Why this is a false positive")


# ============================================================================
# ZONE OCCUPANCY SCHEMAS (Perception -> Backend -> Frontend)
# ============================================================================

class ZoneOccupancy(BaseModel):
    """
    Live occupancy status sent regularly by perception module.
    """
    zone: str
    current_count: int = Field(..., ge=0)
    capacity: int = Field(..., ge=1)
    occupancy_percentage: float = Field(..., ge=0, le=200)
    timestamp: str
    trend: Optional[Literal["increasing", "stable", "decreasing"]] = None

class ZoneOccupancyOut(BaseModel):
    """
    Response for /occupancy endpoints and WebSocket broadcasts.
    Matches the DB model fields exactly.
    """
    zone: str
    current_count: int
    capacity: int
    occupancy_percentage: float
    timestamp: str
    trend: Optional[str] = None
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)